config/routes.rb
Rails.application.routes.draw do
    get 'choose_city' => 'city#choose_city'
    get 'restaurants/index'
    get 'index' => 'restaurants#index'
    get 'get_city' => 'city#get_city'
    match '/', to: 'restaurants#index', constraints: { subdomain: 'www' }, via: [:get, :post, :put, :patch, :delete]
    match '/', to: 'restaurants#index', constraints: { subdomain: "/.+/" }, via: [:get, :post, :put, :patch, :delete]
    root 'restaurants#index'
    resources :search, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class City < ApplicationRecord
    has_many :zones
end

app/models/local.rb
# == Schema Information
#
# Table name: locals
#
#  id            :integer          not null, primary key
#  phone         :string
#  schedule      :string
#  restaurant_id :integer
#  zone_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Local < ApplicationRecord
  belongs_to :restaurant
  belongs_to :zone
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id           :integer          not null, primary key
#  name         :string
#  img_url      :string
#  specialty_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Restaurant < ApplicationRecord
    has_many :locals
    belongs_to :specialty
end

app/models/specialty.rb
# == Schema Information
#
# Table name: specialties
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Specialty < ApplicationRecord
    has_many :restaurants
end

app/models/zone.rb
# == Schema Information
#
# Table name: zones
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :string
#  city_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Zone < ApplicationRecord
    has_many :locals
    belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def require_city
        unless request.subdomain != "" && request.subdomain != 'www'
            redirect_to choose_city_path
        end
    end

    def current_city
        City.find_by(name: request.subdomain.humanize)
    end
end

app/controllers/city_controller.rb
class CityController < ApplicationController
    def choose_city
        @cities = City.all
    end

    def get_city
        id = params[:city_id]
        if id
            redirect_to root_url(subdomain: City.find(id).name)
        else
            flash[:danger] = "An error occured. Please try again"
            redirect_to root_path
        end
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
before_action :require_city

    def index
        @zones = current_city.zones.sort { |a,b| a.name.downcase <=> b.name.downcase }
        @locals = Local.joins(:zone, :restaurant).where('zones.city_id = ?', current_city.id)
        @specialties = Specialty.joins(restaurants: [{locals: :zone}]).where("zones.city_id = ?", 1).uniq.sort { |a,b| a.name.downcase <=> b.name.downcase }
        @restaurants = []
        if params[:query].present?
            @restaurants = Restaurant.where("restaurants.name ILIKE ?", "%#{params[:query]}%").joins({locals: :zone}).where("city_id= ?" , current_city).uniq
        elsif params[:zones].present?
            @restaurants = Restaurant.joins({locals: :zone}).where("city_id= ? and zone_id = ?" , current_city, params[:zones]).uniq
        elsif params[:specialties].present?
            @restaurants = Restaurant.where('specialty_id = ?', params[:specialties]).joins({locals: :zone}).where("city_id= ?", current_city).uniq
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def get_cities(collection)
        puts collection.inspect
        cities = []
        collection.locals.each do |n|
            cities << n.zone.city.name
        end
        cities
    end
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/city/choose_city.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Elige Ciudad</h4>
            </div>
            <%= form_tag(get_city_path, method: "get") do %>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <%= label_tag "ciudad" %>
                                <%= select_tag(:city_id, options_from_collection_for_select(@cities, "id", "name"),{prompt:"Seleccione Ciudad" , class: 'form-control'}) %>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <%= submit_tag "Entrar", class: 'btn btn-success' %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Encuentra Tu Restaurante", root_path, class:"navbar-brand"  %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Cambiar Ciudad: #{request.subdomain.humanize}", root_url(:host => request.domain), class:"navbar-brand" %></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Search</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
</body>
</html>

app/views/restaurants/_form.html.erb
<div class="col-md-4">
    <%= form_tag(root_path, method: "get") do %>
    <div class="input-group">
        <% if action == "zone" %>
            <%= select_tag(:zones, options_from_collection_for_select(@zones, "id", "name"),{prompt:"Seleccione Zona" , class: 'form-control'}) %>
        <% elsif action == "restaurant"%>
             <%= text_field_tag(:query, nil, {class: 'form-control', placeholder: "Buscar Restaurante"}) %>
        <% else %>
            <%= select_tag(:specialties, options_from_collection_for_select(@specialties, "id", "name"),{prompt:"Seleccione Especialidad" , class: 'form-control'}) %>
        <% end %>
        <%= submit_tag("Search", class: "btn btn-default") %>
    </div>
    <% end %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
    <div class="row ">
        <div class="col-md-12">
            <h3 class="text-center">Buscar Por:</h3>
            <div class="forms">
                <%= render 'form', action: 'zone' %>
                <%= render 'form', action: 'restaurant' %>
                <%= render 'form', action: 'specialty' %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="restaurants">
                <% @restaurants.each do |restaurant| %>
                <div class="col-md-12">
                    <div class="jumbotron">
                        <h2 class= "text-center"><%= restaurant.name %></h2>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="info">
                                    <h4><strong> Especialidad: </strong><%= restaurant.specialty.name %></h4>
                                    <h4><strong> Ciudad(es): </strong> <%= get_cities(restaurant).uniq.join(", ") %> </h4>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="image">
                                    <img src="<%= restaurant.img_url %>" alt="...">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <h3 class="text-center">Locales</h3>
                                <div class="locals">
                                    <% restaurant.locals.each do |local| %>
                                        <div class="restaurant">
                                            <%# if (local.zone.city.name == request.subdomain.humanize) %>
                                                <h5><strong> Ciudad: </strong><%= local.zone.city.name %></h5>
                                                <h5><strong> Teléfono: </strong><%= local.phone %></h5>
                                                <h5> <%= "#{local.zone.address} Local: #{local.id}" %></h5>
                                                <h5> <%= local.schedule %></h5>
                                            <%# end %>
                                        </div>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>